baseURL = "/"
languageCode = "en-us"
title = "Ryan Faulhaber"
theme = "duotone-theme-hugo"
enableEmoji = true
description = "Site for Ryan Faulhaber"
#googleAnalytics = "UA-23680267-3"

[params]
	theme = "sea"
    gtag = "UA-23680267-3"


[[menu.header]]
name = "working with me"
url = "working/"

[[menu.header]]
name = "resume"
url = "resume/"

[[menu.header]]
name = "posts"
url = "posts/"

[taxonomies]
    series = "series"
    tags = "tags"

[privacy.googleAnalytics]
anonymizeIP = true
respectDoNotTrack = true
useSessionStorage = true

[markup.highlight]
lineNos = true
codeFences = false
lineNumbersInTable = true
noClasses = true
style = "solarized-dark"
tabWidth = 4

[markup.goldmark.renderer]
unsafe= true
