baseURL = "/"
languageCode = "en-us"
title = "Ryan Faulhaber"
theme = "duotone-theme-hugo"
enableEmoji = true
description = "Site for Ryan Faulhaber"
googleAnalytics = "UA-23680267-3"

[params]
	theme = "sea"

	[[menu.header]]
		name = "about"
        title = "About"
		url = "about/"

	[[menu.header]]
		name = "resume"
        title = "Resume"
		url = "/resume.html"

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = true

[markup]
  [markup.highlight]
	lineNos = true
    codeFences = false
    lineNumbersInTable = true
    noClasses = true
    style = "solarized-dark"
    tabWidth = 4
