baseURL = "/"
languageCode = "en-us"
title = "Ryan Faulhaber"
theme = "hugo-theme-basic"
enableEmoji = true
description = "Basic personal site theme styled with minimal tachyons, syntax highlighting, and blog series configuration."
googleAnalytics = "UA-23680267-3"

[[params.menu]]
    name = "about"
    url = "about/"

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = true
