baseURL = "/"
languageCode = "en-us"
title = "Ryan Faulhaber"
theme = "archie"
enableEmoji = true
description = "Site for Ryan Faulhaber"

[params]
    gtag = "UA-23680267-3"
	mode="auto"


[[menu.main]]
name = "working with me"
url = "working/"

[[menu.main]]
name = "resume"
url = "resume/"

[[menu.main]]
name = "posts"
url = "posts/"

[taxonomies]
    series = "series"
    tags = "tags"

[privacy.googleAnalytics]
anonymizeIP = true
respectDoNotTrack = true
useSessionStorage = true

[markup.highlight]
lineNos = true
codeFences = false
lineNumbersInTable = true
noClasses = true

[markup.goldmark.renderer]
unsafe= true

[markup.goldmark.extensions]
footnote = true
